-- Active: 1723632330684@@127.0.0.1@5433@record
CREATE TABLE IF NOT EXISTS users(
    uuid integer generated by default as identity primary key,
    login text not null unique,
    password_hash text not null,
    salt text not null
);